services:
  - type: worker
    name: instagram-tracker-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python worker.py
    envVars:
      - key: NOTION_API_KEY
        sync: false
      - key: NOTION_DATABASE_ID
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: RUN_IMMEDIATELY
        value: "false"
    scaling:
      minInstances: 1
      maxInstances: 1